FROM ghcr.io/osgeo/gdal:ubuntu-small-3.11.0

# Bounding box in EPSG:2154
ENV XMIN=720000
ENV YMIN=6690000
ENV XMAX=730000
ENV YMAX=6700000
# CRS
ENV CRS="EPSG:2154"
# IMAGE SIZE IN PIXELS
ENV WIDTH=10000
ENV HEIGHT=10000
# WMS LAYER NAME
ENV LAYER="RGEALTI-MNT_PYR-ZIP_FXX_LAMB93_WMS"
# OUTPUT RASTER FORMAT
ENV FORMAT="image/geotiff"
# OUTPUT FILE NAME
ENV OUTPUT_FILE_NAME="dtm.tif"
# BLOCK SIZE FOR DOWNLOAD
ENV BLOCK_SIZE=4096
# MAX CONNECTIONS
ENV MAX_CONN=8
# RASTER BAND COUNT (1 FOR DTM, 3 FOR RGB, ...)
ENV BAND_COUNT=1
# TIMEOUT
ENV TIMEOUT=3600

WORKDIR /app
COPY --chmod=644 wms_conf.xml /app
COPY --chmod=755 script.sh /app
RUN apt-get update && apt-get install gettext -y
CMD ["bash", "/app/script.sh"]
